# Generated by Django 5.0.7 on 2024-12-07 19:58

import crm.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('court_type', models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Traffic', 'Traffic'), ('Appeals', 'Appeals')], default='Civil', max_length=100)),
                ('judge_count', models.PositiveIntegerField(default=1)),
                ('established_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('name', models.CharField(default='Unnamed Category', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Reporting Officer', 'Reporting Officer'), ('Investigating Officer', 'Investigating Officer')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='crm_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='crm_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description provided.')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('date_reported', models.DateField(default=datetime.date.today)),
                ('years_of_imprisonment', models.PositiveIntegerField(default=0)),
                ('imprisonment_type', models.CharField(choices=[('Simple Imprisonment', 'Simple Imprisonment'), ('Hard Labour', 'Hard Labour')], default='Simple Imprisonment', max_length=50)),
                ('officer_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crime_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crimecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('suspect_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Case Closed', 'Case Closed')], default='Pending', max_length=50)),
                ('assigned_officer', models.ForeignKey(limit_choices_to={'role': 'Investigating Officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('crime_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.crime')),
            ],
            options={
                'verbose_name': 'Criminal Record',
                'verbose_name_plural': 'Criminal Records',
                'ordering': ['-date_reported'],
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('court_name', models.CharField(max_length=255)),
                ('hearing_date', models.DateField()),
                ('judge', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('Guilty', 'Guilty'), ('Not Guilty', 'Not Guilty'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('date_filed', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Active', max_length=50)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.court')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crime')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criminalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='Open', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.complainant')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criminalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/', validators=[crm.models.validate_file_type])),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='crm.criminalrecord')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'Reporting Officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('date_of_hire', models.DateField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('rank', models.CharField(default='Unranked', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('officers_in_charge', models.ManyToManyField(to='crm.officer')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.policestation'),
        ),
        migrations.CreateModel(
            name='ReportingOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('date_of_hire', models.DateField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('rank', models.CharField(default='Unranked', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.policestation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('criminal_record', models.TextField(blank=True, null=True)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courtcase')),
            ],
        ),
    ]
