# Generated by Django 5.0.7 on 2024-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingofficer',
            name='office_location',
        ),
        migrations.AddField(
            model_name='crime',
            name='imprisonment_type',
            field=models.CharField(choices=[('Simple Imprisonment', 'Simple Imprisonment'), ('Hard Labour', 'Hard Labour')], default='Simple Imprisonment', max_length=50),
        ),
        migrations.AddField(
            model_name='crime',
            name='years_of_imprisonment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='badge_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
