# Generated by Django 5.0.7 on 2024-12-03 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initialize_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingofficer',
            name='date_of_hire',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Case Closed', 'Case Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportingofficer',
            name='badge_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reportingofficer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('date_of_hire', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
