# Generated by Django 5.0.7 on 2024-12-05 19:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_reportingofficer_date_of_hire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('court_type', models.CharField(choices=[('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Family', 'Family'), ('Traffic', 'Traffic'), ('Appeals', 'Appeals')], default='Civil', max_length=100)),
                ('judge_count', models.PositiveIntegerField(default=1)),
                ('established_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='category',
            new_name='crime_category',
        ),
        migrations.AddField(
            model_name='crime',
            name='date_reported',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='crime',
            name='officer_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='crimecategory',
            name='name',
            field=models.CharField(default='Unnamed Category', max_length=255),
        ),
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='rank',
            field=models.CharField(default='Unranked', max_length=50),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='rank',
            field=models.CharField(default='Unranked', max_length=50),
        ),
        migrations.AlterField(
            model_name='crime',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=255)),
                ('complainant_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='Open', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.complainant')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criminalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('court_name', models.CharField(max_length=255)),
                ('hearing_date', models.DateField()),
                ('judge', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('Guilty', 'Guilty'), ('Not Guilty', 'Not Guilty'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('date_filed', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Active', max_length=50)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.court')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crime')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.criminalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('officers_in_charge', models.ManyToManyField(to='crm.officer')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.policestation'),
        ),
        migrations.AddField(
            model_name='reportingofficer',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.policestation'),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('criminal_record', models.TextField(blank=True, null=True)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courtcase')),
            ],
        ),
    ]
